USE master
GO

DROP DATABASE IF EXISTS NajlepszeZoo

CREATE DATABASE NajlepszeZoo

USE NajlepszeZoo
GO

CREATE TABLE Dieta (
id AUTO_INCREMENT NOT NULL PRIMARY KEY,
typ INT NOT NULL,
przysmak VARCHAR(30),
nazwa VARCHAR(20)
)

CREATE TABLE Lokacje (
id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
miasto VARCHAR(50) NOT NULL,
adres VARCHAR(50) NOT NULL,
tel_kontaktowy CHAR(12) NOT NULL
)

CREATE TABLE Zwierzeta (
id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
imie VARCHAR(20) NOT NULL,
gatunek VARCHAR(30) NOT NULL,
wiek INT NOT NULL,
dieta_id INT REFERENCES Dieta(id),
lokacja_id INT REFERENCES Lokacje(id)
)